-- =============================================================
-- Lookbook Estilos 2.0: +82 combinações, uma por foto nova das
-- galerias (inclui os estilos novos techwear, skater e quietluxury).
-- Aplicada em produção via REST em 2026-07-12.
-- =============================================================

insert into public.looks (title, description, occasion, style, climate, level, base_color, image_url, pieces, why_it_works, adaptations) values
('Xadrez Aberto & Jordan Oliva', 'Dia a dia com camadas leves e joias douradas.', 'dia-a-dia', 'streetwear', 'meia-estacao', 'avancado', 'bege', '/estilos/streetwear/11.jpg',
'["Camisa xadrez de manga curta aberta", "Camiseta branca por baixo", "Baggy jeans de lavagem suja", "Jordan 4 (ou tênis robusto) verde-oliva", "Correntes e anéis dourados"]',
'A camisa xadrez aberta funciona como terceira peça leve, e o dourado dos acessórios aquece a paleta lavada do jeans.',
'["Trocar a xadrez por overshirt lisa para simplificar", "Fechar a camisa e tirar os anéis para versão discreta"]'),
('Camo & Tênis Amarelo', 'Verão urbano com um só ponto de cor.', 'dia-a-dia', 'streetwear', 'calor', 'intermediario', 'verde', '/estilos/streetwear/12.jpg',
'["Camiseta branca oversized", "Bermuda cargo camuflada de corte amplo", "Tênis statement amarelo", "Boné verde-oliva", "Óculos escuros"]',
'Base branca + camo é fórmula segura; o tênis amarelo entra como único ponto de cor forte e vira o centro do look.',
'["Trocar o tênis amarelo por branco para versão fácil", "Trocar camo por jorts cinza"]'),
('Zip Hoodie & Jorts Preto', 'O uniforme street de meia-estação.', 'faculdade', 'streetwear', 'meia-estacao', 'intermediario', 'preto', '/estilos/streetwear/13.jpg',
'["Zip hoodie navy com box logo", "Camiseta branca por baixo", "Jorts preto de corte carpenter", "Cinto western com fivela prata", "Tênis de skate e meia branca aparente"]',
'O navy do hoodie sobre o preto do jorts cria profundidade sem cor extra — e o cinto western dá o detalhe que separa do básico.',
'["Trocar jorts por baggy jeans no frio", "Trocar o cinto western por um liso para simplificar"]'),
('Verde & Bucket de Crochê', 'Peça statement com bota de trilha urbana.', 'evento-casual', 'streetwear', 'meia-estacao', 'avancado', 'verde', '/estilos/streetwear/14.jpg',
'["Manga longa canelada verde com gráfico", "Bucket hat de crochê amarelo", "Baggy jeans escuro desbotado", "Bota amarela tipo Timberland", "Pulseiras coloridas"]',
'Verde e amarelo dividem a mesma temperatura de cor, então as duas peças fortes conversam em vez de competir.',
'["Trocar o bucket por boné para reduzir a ousadia", "Versão neutra: mesma fórmula com moletom cinza"]'),
('Camadas & Baggy Gigante', 'Proporção máxima com paleta fechada.', 'dia-a-dia', 'streetwear', 'meia-estacao', 'avancado', 'preto', '/estilos/streetwear/15.jpg',
'["Camiseta preta lavada com gráfico sobre manga longa branca", "Baggy jeans cinza-escuro extralargo", "Cinto western claro", "Bota amarela de trabalho", "Boné branco e correntes"]',
'A manga longa branca aparecendo sob a camiseta é a camada Y2K clássica — e a bota clara equilibra o volume escuro da calça.',
'["Reduzir o volume da calça para baggy comum", "Trocar bota por tênis chunky preto"]'),
('Cowboy em Cinza', 'Jorts de moletom e atitude retrô-western.', 'dia-a-dia', 'streetwear', 'calor', 'intermediario', 'cinza', '/estilos/streetwear/16.jpg',
'["Camiseta branca cropped com gráfico western", "Jorts de moletom cinza volumoso", "Tênis preto volumoso", "Gorro camuflado", "Corrente militar (ball chain)"]',
'O jorts de moletom dá o volume confortável e o gráfico western + gorro criam o contraste de referências que define o street atual.',
'["Trocar gorro por boné no calor forte", "Versão limpa: camiseta lisa branca no lugar da gráfica"]'),
('Jersey Azul-Bebê', 'A camisa de futebol americano como peça central.', 'evento-casual', 'streetwear', 'calor', 'intermediario', 'azul', '/estilos/streetwear/17.jpg',
'["Jersey retrô azul-claro", "Camiseta branca por baixo", "Bermuda cargo jeans", "Tênis branco", "Bandana branca na cabeça"]',
'O jersey oversized já traz cor e história; o resto do look fica em denim e branco para deixar a camisa brilhar.',
'["Trocar bandana por boné", "Usar calça baggy no lugar da bermuda à noite"]'),
('Polo Verde & Alfaiataria Preta', 'Street elevado para a noite.', 'noite', 'streetwear', 'meia-estacao', 'avancado', 'verde', '/estilos/streetwear/18.jpg',
'["Polo boxy verde com gráfico retrô", "Calça preta ampla de pregas", "Sapato/bota de trilha marrom", "Boné preto e óculos de lente laranja", "Cinto estampado e corrente dourada"]',
'Polo gráfica sobre alfaiataria preta é a mistura street + arrumado que domina a cena — o marrom do calçado tira o look do óbvio.',
'["Trocar o sapato de trilha por loafer para jantar", "Sem óculos e cinto estampado para versão sóbria"]'),
('Cinza, Denim & Timberland', 'Fórmula fácil de frio ameno.', 'dia-a-dia', 'streetwear', 'meia-estacao', 'facil', 'cinza', '/estilos/streetwear/19.jpg',
'["Zip hoodie cinza", "Regata ou camiseta branca por baixo", "Baggy jeans de lavagem clara", "Bota amarela tipo Timberland", "Boné preto NY"]',
'Cinza + denim claro + bota caramelo: três neutros que sempre fecham. O zíper meio aberto mostra a camada branca e dá profundidade.',
'["Trocar bota por tênis branco no calor", "Adicionar puffer por cima no frio de verdade"]'),
('Shell Azul & Cargo Militar', 'Dia de chuva com utilidade máxima.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'intermediario', 'azul', '/estilos/gorpcore/16.jpg',
'["Jaqueta shell impermeável azul", "Calça cargo militar verde-sage", "Tênis de trail cinza", "Bolsa crossbody utilitária"]',
'Azul técnico sobre verde militar é a dupla de cores mais clássica do gorpcore — e cada peça tem função real.',
'["Trocar a cargo por jeans reto para simplificar", "Adicionar fleece por baixo no frio"]'),
('Mountain Jacket Vermelha', 'Peça técnica statement com camo.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'avancado', 'verde', '/estilos/gorpcore/17.jpg',
'["Mountain jacket vermelha e preta", "Camiseta branca por baixo", "Bermuda cargo camuflada volumosa", "Tênis de trail preto e amarelo", "Boné estampado e meião branco"]',
'Vermelho + camo + trail shoes só funciona porque cada peça é técnica de verdade — o branco no meio separa os padrões.',
'["Trocar a bermuda camo por cargo preta", "Versão fria: mesma jaqueta com calça técnica"]'),
('All Black de Trilha', 'Verão funcional em preto total.', 'dia-a-dia', 'gorpcore', 'calor', 'facil', 'preto', '/estilos/gorpcore/18.jpg',
'["Camiseta preta oversized", "Shorts de nylon preto com gráfico tonal", "Tênis de trail com detalhes amarelos", "Meia branca aparente"]',
'All black de tecidos técnicos não pesa nem no calor — e o amarelo do tênis é o único acento necessário.',
'["Trocar shorts de nylon por cargo curta", "Adicionar windbreaker amarrada na cintura"]'),
('Gradiente Laranja', 'Shell vibrante sobre denim lavado.', 'evento-casual', 'gorpcore', 'meia-estacao', 'avancado', 'azul', '/estilos/gorpcore/19.jpg',
'["Jaqueta shell laranja em degradê", "Camiseta branca", "Baggy jeans de lavagem bem clara", "Tênis laranja", "Boné NY navy e óculos esportivos"]',
'O tênis repete o laranja da jaqueta e fecha o look em sanduíche de cor — técnica de quem domina o estilo.',
'["Tênis branco para acalmar o visual", "Trocar jeans por cargo cinza técnica"]'),
('Goggle Jacket', 'Referência técnica italiana no inverno urbano.', 'noite', 'gorpcore', 'frio', 'intermediario', 'branco', '/estilos/gorpcore/20.jpg',
'["Jaqueta branca com capuz e goggles (estilo CP Company)", "Track pants preta volumosa", "Tênis de corrida cinza", "Camadas térmicas por baixo"]',
'O contraste branco sobre preto deixa a jaqueta de goggles como protagonista absoluta — o resto só dá suporte.',
'["Trocar track pants por cargo técnica", "Versão dia: camiseta branca e jeans reto"]'),
('Shell Mostarda & Air Max', 'Cor de montanha no meio da cidade.', 'faculdade', 'gorpcore', 'meia-estacao', 'intermediario', 'preto', '/estilos/gorpcore/21.jpg',
'["Jaqueta shell mostarda", "Bermuda cargo preta volumosa", "Air Max 95 (cinza com neon)", "Meião branco"]',
'O neon do tênis conversa com o mostarda da shell — paleta técnica clássica dos anos 90 aplicada no dia a dia.',
'["Trocar bermuda por calça técnica no frio", "Shell preta para versão discreta"]'),
('Estampa Koi', 'Shell estampada como peça única de destaque.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'avancado', 'azul', '/estilos/gorpcore/22.jpg',
'["Jaqueta shell azul estampada", "Baggy jeans de lavagem média", "Gorro preto", "Óculos de grau estilosos", "Tênis técnico cinza e branco"]',
'Quando a jaqueta é estampada, o resto fica em denim e preto — regra de ouro para peças statement.',
'["Trocar gorro por boné", "Jeans preto para look noturno"]'),
('Laranja & Carpenter Jorts', 'Cor técnica com denim de trabalho.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'intermediario', 'azul', '/estilos/gorpcore/23.jpg',
'["Jaqueta shell laranja com capuz", "Camiseta branca", "Jorts carpenter azul", "Air Force 1 preto", "Meia branca aparente"]',
'A shell laranja vitaminada sobre o jorts azul cria contraste complementar — e o AF1 preto ancora tudo.',
'["Trocar jorts por cargo no frio", "Tênis branco para clarear a base"]'),
('Amarelo-Manteiga & Índigo', 'Cor suave executada com precisão.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'azul', '/estilos/minimalista/16.jpg',
'["Camiseta amarelo-manteiga com bolso", "Jeans índigo escuro amplo com barra dobrada", "Sapato ou tênis preto minimalista", "Boné navy e óculos de grau"]',
'Amarelo-manteiga é a cor pastel mais fácil de usar — sobre índigo escuro, fica sofisticada sem esforço.',
'["Trocar sapato por tênis branco", "Camiseta branca para versão zero risco"]'),
('Ringer Marrom & Off-White', 'Retrô mínimo com paleta de café.', 'date', 'minimalista', 'calor', 'intermediario', 'marrom', '/estilos/minimalista/17.jpg',
'["Camiseta ringer marrom com friso azul", "Calça off-white de corte amplo", "Tênis de camurça azul", "Bolsa de ombro marrom", "Cinto fino escuro"]',
'Marrom + off-white + um toque de azul: paleta de três cores exatas, cada uma aparecendo duas vezes no look.',
'["Trocar bolsa por versão preta discreta", "Calça bege se o off-white intimidar"]'),
('Bermuda de Alfaiataria', 'O shorts elegante do verão.', 'faculdade', 'minimalista', 'calor', 'facil', 'bege', '/estilos/minimalista/18.jpg',
'["Camiseta off-white com gráfico pequeno", "Bermuda bege de pregas e corte amplo", "adidas Superstar (ou tênis branco clássico)", "Meia branca aparente", "Boné claro"]',
'A bermuda de alfaiataria substitui o shorts comum e eleva o look inteiro — o resto pode ser básico.',
'["Camiseta lisa para versão mais limpa", "Trocar Superstar por mocassim no jantar"]'),
('Preto Lavado & Cinza', 'Monocromático com textura de lavagem.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'cinza', '/estilos/minimalista/19.jpg',
'["Camiseta boxy preta lavada", "Baggy jeans cinza-claro desbotado", "Tênis vinho e branco", "Pulseiras discretas"]',
'Preto lavado sobre cinza lavado cria um degradê natural — e o tênis vinho é o detalhe que mostra intenção.',
'["Tênis branco para o básico absoluto", "Calça preta para look tonal escuro"]'),
('Amarelo & Cor de Pedra', 'Gráfico retrô sobre neutros quentes.', 'faculdade', 'minimalista', 'calor', 'intermediario', 'bege', '/estilos/minimalista/20.jpg',
'["Camiseta amarela com gráfico verde", "Calça baggy cor de pedra", "Sapato ou tênis preto", "Boné verde", "Tote bag preta"]',
'O boné repete o verde do gráfico e a calça neutraliza — três cores no total, tudo conectado.',
'["Camiseta branca para acalmar", "Trocar tote por mochila no dia corrido"]'),
('Camisa Azul-Céu Aberta', 'Frescor de verão com bota caramelo.', 'date', 'minimalista', 'calor', 'intermediario', 'azul', '/estilos/minimalista/21.jpg',
'["Camisa azul-claro de manga curta aberta", "Regata branca canelada", "Baggy jeans de lavagem média", "Bota ou clog caramelo", "Colar de pérolas discreto"]',
'A camisa aberta funciona de terceira peça leve e o caramelo do calçado aquece a paleta fria do azul.',
'["Fechar a camisa e tirar o colar para versão clássica", "Tênis branco no lugar da bota"]'),
('Tricô no Ombro', 'O truque de estilista para look de noite.', 'noite', 'minimalista', 'meia-estacao', 'avancado', 'preto', '/estilos/minimalista/22.jpg',
'["Camiseta branca encorpada", "Suéter cinza drapeado no ombro", "Calça preta ampla de pregas", "Loafer preto com detalhe", "Boné navy e relógio de aço"]',
'O tricô jogado no ombro adiciona camada e nonchalance sem esquentar — truque clássico de editorial.',
'["Vestir o suéter se esfriar (o look continua pronto)", "Trocar loafer por tênis branco de dia"]'),
('Branco & Taupe', 'Dois tons, zero esforço aparente.', 'date', 'minimalista', 'calor', 'facil', 'marrom', '/estilos/minimalista/23.jpg',
'["Camiseta branca de caimento justo", "Jeans taupe/marrom-claro de corte amplo", "Cinto de couro marrom", "Sapato de couro marrom", "Anéis e pulseira prata"]',
'Camiseta ajustada + calça volumosa é o contraste de proporção que valoriza o corpo — e o marrom unifica cinto e sapato.',
'["Tênis branco para versão diurna", "Adicionar camisa aberta como terceira peça"]'),
('Navy & Alfaiataria', 'Uniforme urbano de quem entende de caimento.', 'noite', 'minimalista', 'meia-estacao', 'facil', 'preto', '/estilos/minimalista/24.jpg',
'["Camiseta navy oversized com logo discreto", "Calça preta ampla de alfaiataria", "Loafer preto e branco", "Trucker cap creme", "Óculos escuros retangulares"]',
'Navy sobre preto é a combinação que poucos arriscam e sempre funciona — o boné claro ilumina o conjunto.',
'["Trocar loafer por tênis limpo", "Camiseta preta para monocromático total"]'),
('Listras & Alfaiataria Cinza', 'O clássico do verão europeu.', 'trabalho', 'oldmoney', 'calor', 'intermediario', 'azul', '/estilos/oldmoney/13.jpg',
'["Camisa listrada azul com mangas dobradas", "Calça cinza de pregas", "Cinto preto de couro", "Loafer preto", "Correntes douradas e óculos escuros"]',
'Camisa entreaberta com mangas dobradas tira a rigidez da alfaiataria — elegância com temperatura de verão.',
'["Fechar mais botões para ambiente formal", "Trocar loafer por tênis branco no fim de semana"]'),
('Bermuda Bege & Cinza', 'Old money casual de fim de semana.', 'dia-a-dia', 'oldmoney', 'calor', 'facil', 'bege', '/estilos/oldmoney/14.jpg',
'["Camiseta cinza encorpada", "Bermuda bege de alfaiataria", "Tênis camurça navy", "Meia branca", "Boné marrom e óculos escuros"]',
'A bermuda de pregas eleva a camiseta cinza comum — e o navy do tênis fecha a paleta de neutros clássicos.',
'["Trocar camiseta por polo para almoço arrumado", "Mocassim sem meia para versão riviera"]'),
('Preto Total Elegante', 'Noite sofisticada em uma cor.', 'noite', 'oldmoney', 'meia-estacao', 'intermediario', 'preto', '/estilos/oldmoney/15.jpg',
'["Camiseta preta de caimento justo", "Calça preta fluida de corte amplo", "Cinto com fivela discreta", "Loafer ou sapato preto", "Relógio prata e bolsa de couro"]',
'All black em tecidos bons e cortes precisos é o atalho mais confiável para presença à noite.',
'["Trocar camiseta por polo de malha", "Adicionar blazer se o ambiente pedir"]'),
('Oxford & Birkenstock', 'Férias mediterrâneas sem esforço.', 'viagem', 'oldmoney', 'calor', 'facil', 'branco', '/estilos/oldmoney/16.jpg',
'["Camisa oxford azul-claro folgada", "Shorts off-white de pregas", "Birkenstock ou clog de camurça", "Meia branca", "Boné vermelho e tote de lona"]',
'A camisa aberta sobre shorts claro é o uniforme de férias old money — o boné vermelho dá o toque de cor descontraído.',
'["Sem meia para versão praia", "Mocassim de couro para jantar no destino"]'),
('Colete de Tricô & Gravata', 'Herança britânica com atitude atual.', 'evento-casual', 'oldmoney', 'meia-estacao', 'avancado', 'verde', '/estilos/oldmoney/17.jpg',
'["Colete de tricô verde-oliva", "Camisa listrada com gravata escura", "Calça preta de pregas", "Cinto trançado e loafer preto", "Boina xadrez (flat cap)"]',
'Colete + gravata + boina é vintage acadêmico puro — os tons terrosos impedem que pareça fantasia.',
'["Tirar a gravata para versão relaxada", "Trocar boina por cabelo penteado e óculos"]'),
('Riviera Navy & Branco', 'O look de verão mais elegante que existe.', 'date', 'oldmoney', 'calor', 'avancado', 'branco', '/estilos/oldmoney/18.jpg',
'["Camisa listrada azul e branca", "Suéter navy amarrado nos ombros", "Calça branca de corte amplo", "Sandália de couro preta", "Boné navy e relógio"]',
'Navy sobre listras sobre branco: a tríade riviera. O suéter no ombro é a terceira peça que faz o look.',
'["Loafer no lugar da sandália para jantar", "Bermuda branca para versão praia"]'),
('Rugby & Flanela Cinza', 'Colegial americano revisitado.', 'faculdade', 'oldmoney', 'meia-estacao', 'intermediario', 'vinho', '/estilos/oldmoney/19.jpg',
'["Camisa rugby listrada vinho e navy", "Calça cinza de lã fria ampla", "Loafer preto", "Boné navy NY", "Fones de ouvido como acessório"]',
'A rugby entra no lugar do moletom e muda o nível do look — as listras largas pedem o resto liso.',
'["Tênis branco para versão campus", "Trocar calça por chino bege"]'),
('Camisa & Wallabee', 'Manhã de sábado bem vestida.', 'dia-a-dia', 'oldmoney', 'calor', 'facil', 'branco', '/estilos/oldmoney/20.jpg',
'["Camisa listrada azul-claro", "Jeans off-white reto", "Wallabee ou mocassim de camurça", "Boné azul e óculos de grau", "Pulseira dourada fina"]',
'Listras claras sobre off-white é frescor total — o Wallabee dá textura sem quebrar a leveza.',
'["Dobrar as mangas no calor forte", "Trocar jeans claro por chino bege"]'),
('Polo & Creme Total', 'Golden hour em Paris.', 'date', 'oldmoney', 'calor', 'intermediario', 'branco', '/estilos/oldmoney/21.jpg',
'["Polo branca de piquet", "Suéter creme amarrado nos ombros", "Calça creme de pregas", "Tênis branco limpo", "Cinto marrom e relógio prata"]',
'Tons de branco e creme em camadas criam riqueza sem nenhuma cor — o cinto marrom define a cintura do look.',
'["Mocassim para jantar", "Polo navy se quiser contraste"]'),
('Mohair Azul-Bebê', 'Tricô statement com jeans claro.', 'dia-a-dia', 'oldmoney', 'frio', 'facil', 'azul', '/estilos/oldmoney/22.jpg',
'["Suéter de mohair azul-claro", "Camiseta branca aparecendo na barra", "Jeans claro de corte reto amplo", "Tênis branco", "Tote verde e óculos escuros"]',
'A textura felpuda do mohair é o luxo silencioso da peça — azul sobre azul claro alonga a silhueta.',
'["Trocar tote por mochila discreta", "Bota chelsea no frio úmido"]'),
('Bomber Greige & Gravata', 'Tailoring moderno sem blazer.', 'noite', 'quietluxury', 'meia-estacao', 'avancado', 'bege', '/estilos/quietluxury/01.jpg',
'["Bomber minimalista greige (cinza-bege)", "Camisa branca com gravata preta fina", "Calça preta ampla com leve flare", "Sapato ou loafer escuro", "Boné bege"]',
'A gravata sob o bomber é o choque de formal + casual que define o luxo discreto atual — paleta de três neutros exatos.',
'["Tirar a gravata para versão dia", "Trocar boné por cabelo feito em evento"]'),
('Cardigan Creme & Taupe', 'Texturas caras em tons de areia.', 'date', 'quietluxury', 'meia-estacao', 'intermediario', 'bege', '/estilos/quietluxury/02.jpg',
'["Cardigan creme de tricô encorpado", "Camiseta branca por baixo", "Calça taupe de pregas volumosa", "Sapato de couro preto", "Óculos escuros e anéis prata"]',
'Creme sobre taupe é a paleta quiet luxury por excelência — a qualidade do tricô é o próprio statement.',
'["Trocar sapato por tênis off-white", "Camiseta cinza para mais contraste"]'),
('Gola de Couro', 'Jaqueta com detalhe nobre sobre denim escuro.', 'dia-a-dia', 'quietluxury', 'meia-estacao', 'intermediario', 'bege', '/estilos/quietluxury/03.jpg',
'["Jaqueta bege com gola de couro marrom", "Camiseta branca", "Baggy jeans índigo escuro com barra dobrada", "Cinto de couro marrom", "Loafer escuro e óculos"]',
'A gola de couro é o único detalhe de luxo — e é suficiente. O jeans escuro mantém tudo no chão.',
'["Bota de couro no frio", "Camiseta bege para look tonal"]'),
('Lã Cinza & Toque Vermelho', 'Neutros perfeitos com um acento de cor.', 'evento-casual', 'quietluxury', 'meia-estacao', 'avancado', 'cinza', '/estilos/quietluxury/04.jpg',
'["Jaqueta-cardigan de lã cinza sem gola", "Camisa azul-clara por baixo", "Jeans claro de corte reto", "Sapato de tricô vermelho", "Óculos escuros"]',
'Tudo neutro e impecável — e então o sapato vermelho. Um único acento de cor em material nobre é a assinatura do luxo discreto.',
'["Sapato de couro preto para versão segura", "Trocar jeans por calça de flanela cinza"]'),
('Conjunto Marrom & Gravata', 'Workwear de luxo em tom de chocolate.', 'evento-casual', 'quietluxury', 'meia-estacao', 'avancado', 'marrom', '/estilos/quietluxury/05.jpg',
'["Jaqueta trucker marrom de sarja", "Calça marrom no mesmo tom (conjunto)", "Camisa branca com gravata escura", "Cinto e botas pretas", "Fones over-ear como acessório"]',
'O conjunto monocromático marrom com gravata cria o uniforme de luxo utilitário — sério, raro e memorável.',
'["Separar as peças do conjunto em looks diferentes", "Sem gravata para o dia a dia"]'),
('All Black Discreto', 'A versão luxo do look preto.', 'noite', 'quietluxury', 'meia-estacao', 'intermediario', 'preto', '/estilos/quietluxury/06.jpg',
'["Jaqueta harrington preta de zíper", "Calça preta ampla de pregas", "Loafer de couro preto", "Boné preto NY", "Fones prata e óculos de grau"]',
'Nenhum logo, nenhuma cor: só corte e proporção. O loafer no lugar do tênis muda o nível do all black.',
'["Tênis preto minimalista para versão casual", "Sobretudo no lugar da harrington no frio"]'),
('Shorts de Alfaiataria & Meião', 'Verão de luxo com referência retrô.', 'dia-a-dia', 'quietluxury', 'calor', 'facil', 'preto', '/estilos/quietluxury/07.jpg',
'["Camiseta branca de caimento perfeito", "Shorts preto de pregas", "Meião branco esticado", "Loafer preto e branco", "Boné navy e corrente dourada"]',
'Meião branco com loafer é o detalhe vintage que transforma camiseta + shorts em look editorial.',
'["Tênis branco no lugar do loafer", "Shorts bege para paleta clara"]'),
('Camisa Listrada Amarela', 'Cor rara executada com sobriedade.', 'date', 'quietluxury', 'calor', 'intermediario', 'branco', '/estilos/quietluxury/08.jpg',
'["Camisa oversized listrada amarela", "Calça off-white de corte amplo", "Penny loafer preto", "Óculos escuros e anéis discretos"]',
'Amarelo suave em listras finas é cor sem gritar — sobre off-white, vira o look de verão mais sofisticado da galeria.',
'["Camiseta branca por baixo com camisa aberta", "Sandália de couro no calor extremo"]'),
('Longsleeve de Banda', 'O uniforme skater dos anos 2000.', 'dia-a-dia', 'skater', 'meia-estacao', 'intermediario', 'verde', '/estilos/skater/01.jpg',
'["Camiseta de banda cinza de manga longa", "Jorts camuflado longo e volumoso", "Converse preto de cano alto", "Gorro preto", "Fone de fio (detalhe Y2K)"]',
'Camiseta de banda + camo + Chuck alto é a fórmula skate noventista original — proporções largas fazem o look.',
'["Trocar jorts camo por jeans baggy", "Tênis de skate baixo se preferir"]'),
('Y2K Vermelho & JNCO', 'Volume extremo herdado dos anos 2000.', 'faculdade', 'skater', 'meia-estacao', 'avancado', 'azul', '/estilos/skater/02.jpg',
'["Camiseta vermelha com gráfico Y2K sobre manga longa branca", "Baggy jeans gigante (estilo JNCO)", "Tênis de skate vermelho e branco", "Óculos esportivos prateados"]',
'A calça superlarga é a protagonista; a camada branca sob a camiseta vermelha repete o branco do tênis.',
'["Reduzir para baggy comum se o volume intimidar", "Versão neutra com camiseta preta"]'),
('Cargo Jorts Desfiado', 'Skate de verão com peça garimpada.', 'dia-a-dia', 'skater', 'calor', 'intermediario', 'bege', '/estilos/skater/03.jpg',
'["Camiseta navy desbotada com logo pequeno", "Jorts cargo bege de barra desfiada", "Vans com detalhe rosa", "Meião branco", "Boné azul-claro e mosquetão de chaves"]',
'A barra desfiada e o mosquetão contam a história do estilo — o rosa do tênis é o toque inesperado que funciona.',
'["Vans clássico preto para versão segura", "Trocar jorts por chino bege no arrumado"]'),
('Carpenter Claro & Chunky', 'Denim claro com tênis statement.', 'dia-a-dia', 'skater', 'calor', 'facil', 'branco', '/estilos/skater/04.jpg',
'["Camiseta branca oversized", "Shorts carpenter de jeans claro", "Tênis chunky de cadarço grosso", "Boné snapback com patch"]',
'Base branca + denim claro deixa o tênis de cadarço grosso como único protagonista — fácil de copiar.',
'["Tênis de skate clássico para simplificar", "Adicionar corrente prata no pescoço"]'),
('Harley Desbotada', 'Gráfico vintage com jorts rasgado.', 'dia-a-dia', 'skater', 'meia-estacao', 'intermediario', 'azul', '/estilos/skater/05.jpg',
'["Manga longa cinza lavada com gráfico de moto", "Jorts carpenter claro de barra desfiada", "Meias brancas em camada dupla", "Tênis de skate preto e azul"]',
'A camiseta desbotada de garimpo dá alma; a meia dupla aparente é código de quem vive a cultura.',
'["Trocar manga longa por camiseta no calor", "Jorts escuro para versão noturna"]'),
('Camo Zip & Superstar', 'Referência 2000s da cabeça aos pés.', 'faculdade', 'skater', 'frio', 'intermediario', 'verde', '/estilos/skater/06.jpg',
'["Zip hoodie camuflado com logo colegial", "Camiseta branca aparecendo na barra", "Calça de moletom oliva volumosa", "adidas Superstar branco"]',
'Camo sobre oliva é tom sobre tom militar — e o Superstar branco ilumina a base escura do look.',
'["Moletom cinza no lugar do oliva", "Tênis de skate preto no dia de chuva"]'),
('Conjunto de Moletom Cinza', 'Sweat jorts e hoodie estampado.', 'dia-a-dia', 'skater', 'frio', 'intermediario', 'cinza', '/estilos/skater/07.jpg',
'["Zip hoodie cinza com estampa de jornal", "Jorts de moletom cinza (conjunto)", "adidas Gazelle azul", "Gorro branco felpudo", "Meião branco"]',
'O conjunto de moletom com estampa gráfica é o conforto skatista elevado — o azul do tênis quebra o cinza total.',
'["Hoodie liso para versão discreta", "Calça de moletom no frio de verdade"]'),
('Hoodie Verde Austin', 'College + skate com denim destruído.', 'faculdade', 'skater', 'meia-estacao', 'intermediario', 'verde', '/estilos/skater/08.jpg',
'["Hoodie verde com letras colegiais", "Camiseta branca aparecendo na barra", "Carpenter jeans claro rasgado", "Tênis de skate preto e branco", "Correntes e wallet chain"]',
'O verde college sobre denim claro destruído mistura campus e pista — as correntes fecham a atitude.',
'["Jeans intacto para versão limpa", "Moletom cinza se o verde cansar"]'),
('Trucker & Camo Shorts', 'Denim e camuflado em equilíbrio.', 'dia-a-dia', 'skater', 'meia-estacao', 'intermediario', 'azul', '/estilos/skater/09.jpg',
'["Jaqueta trucker de jeans claro", "Bermuda cargo camuflada volumosa", "Vans Old Skool azul", "Meião branco", "Boné camo e messenger bag preta"]',
'Denim claro em cima, camo embaixo e Vans no pé: três clássicos do skate que dividem a mesma paleta fria.',
'["Camiseta branca sob a trucker aberta", "Calça camo no frio"]'),
('Hoodie & Gorro', 'O básico skatista de inverno.', 'dia-a-dia', 'skater', 'frio', 'facil', 'cinza', '/estilos/skater/10.jpg',
'["Hoodie cinza liso com capuz sobre gorro preto", "Baggy jeans de lavagem suja rasgado", "Converse preto", "Camadas térmicas por baixo"]',
'Capuz sobre gorro é o styling de inverno das pistas — hoodie liso + jeans destruído equilibram simples e gasto.',
'["Jeans limpo para versão neutra", "Vans no lugar do Converse"]'),
('Camadas de Frio Real', 'Três camadas funcionais com paleta terrosa.', 'dia-a-dia', 'techwear', 'frio', 'avancado', 'verde', '/estilos/techwear/01.jpg',
'["Bomber verde-militar lavado", "Tricô de zíper vinho com capuz por baixo", "Camiseta branca na base", "Work jeans preto volumoso", "Tênis de camurça com cadarço vermelho e gorro vinho"]',
'Cada camada tem função térmica e o vinho aparece duas vezes (gorro + tricô) amarrando a paleta.',
'["Remover o bomber em ambiente fechado", "Bota preta no lugar do tênis na chuva"]'),
('All Black Noturno', 'Volume máximo em preto absoluto.', 'noite', 'techwear', 'frio', 'intermediario', 'preto', '/estilos/techwear/02.jpg',
'["Bomber preto oversized", "Hoodie preto por baixo", "Calça preta workwear de boca ampla", "Botas pretas volumosas", "Bolsa de couro preta"]',
'Preto sobre preto em volumes exagerados cria silhueta de vilão de filme — o techwear na sua forma mais pura.',
'["Reduzir para calça reta se o volume pesar", "Trocar bota por sneaker técnico preto"]'),
('Utility Slim & Cargo', 'Contraste de proporção com cinto tático.', 'dia-a-dia', 'techwear', 'meia-estacao', 'avancado', 'preto', '/estilos/techwear/03.jpg',
'["Camiseta preta de gola alta justa", "Cargo paraquedas preto supervolumoso", "Cinto utilitário largo", "Bolsa crossbody de couro", "Tênis de corrida branco"]',
'Torso justo + pernas gigantes é o contraste de silhueta techwear — o tênis branco impede o look de sumir no preto.',
'["Camiseta comum se a segunda pele incomodar", "Tênis preto para monocromático total"]'),
('Funcional Diário', 'Techwear acessível para todo dia.', 'trabalho', 'techwear', 'meia-estacao', 'intermediario', 'preto', '/estilos/techwear/04.jpg',
'["Overshirt preta com bolsos utilitários grandes", "Calça preta balloon com barra ajustada", "Salomon XT-6 (ou trail runner)", "Boné preto e óculos escuros", "Tote bag verde-escuro"]',
'Overshirt de bolsos + Salomon é o techwear que funciona até no escritório casual — funcional sem fantasia.',
'["Camisa social preta por baixo em dia formal", "Trocar tote por mochila técnica"]'),
('Puffer com Letras', 'Inverno statement em preto e cinza.', 'noite', 'techwear', 'frio', 'intermediario', 'preto', '/estilos/techwear/05.jpg',
'["Puffer cinza-escuro com apliques de letras", "Cargo de nylon preto volumoso", "Botas pretas", "Óculos escuros e anéis prata"]',
'O puffer gráfico é a única peça de destaque — nylon sobre nylon mantém a coerência técnica.',
'["Puffer liso preto para versão discreta", "Calça de moletom técnica em dia relax"]'),
('Conforto Técnico', 'O look de aeroporto dos atletas.', 'viagem', 'techwear', 'frio', 'facil', 'preto', '/estilos/techwear/06.jpg',
'["Hoodie preto encorpado", "Track pants grafite de boca ampla", "Tênis de corrida cinza", "Gorro estampado e fones over-ear", "Mochila ou bolsa técnica"]',
'É o uniforme de deslocamento de jogador de NBA: conforto total, mas cada peça com corte e material intencionais.',
'["Trocar track pants por cargo", "Óculos de grau finos elevam o conjunto"]'),
('Nylon & Paraquedas', 'Anonimato futurista urbano.', 'dia-a-dia', 'techwear', 'meia-estacao', 'intermediario', 'preto', '/estilos/techwear/07.jpg',
'["Track jacket de nylon preta com capuz", "Cargo paraquedas cinza-oliva", "Tênis chunky preto", "Fones over-ear"]',
'Nylon farfalhante + cargo de ajustes é a dupla sonora e visual do techwear — o capuz fecha a silhueta.',
'["Cargo preta para versão total black", "Windbreaker colorida para quebrar o sério"]'),
('Couro & Volume', 'A versão couro do techwear.', 'noite', 'techwear', 'meia-estacao', 'avancado', 'preto', '/estilos/techwear/08.jpg',
'["Jaqueta de couro preta com capuz", "Calça balloon preta encerada", "Cinto de tachas", "Botas pretas volumosas", "Correntes e anéis"]',
'Couro com modelagem balloon moderniza o material clássico — brilho sutil da cera dá a textura futurista.',
'["Jaqueta de nylon se o couro pesar", "Menos acessórios para versão sóbria"]'),
('Tático em Camadas', 'Streetwear técnico japonês.', 'dia-a-dia', 'techwear', 'meia-estacao', 'intermediario', 'cinza', '/estilos/techwear/09.jpg',
'["Camiseta grafite sobre manga longa (camadas)", "Cargo tático verde-escuro com fitas", "Camisa xadrez amarrada/pendurada", "Gorro preto", "Tênis preto discreto"]',
'Camiseta sobre manga longa + cargo de tiras é a receita do tech japonês — o xadrez pendurado adiciona movimento.',
'["Remover o xadrez para simplificar", "Trocar cargo tática por cargo comum"]'),
('Listras Verde-Limão', 'Polo retrô com jorts e camurça.', 'dia-a-dia', 'vintage', 'calor', 'intermediario', 'verde', '/estilos/vintage/17.jpg',
'["Polo-camiseta listrada verde e lima", "Jorts de lavagem média desfiado", "Meias franzidas aparentes", "Tênis de camurça caramelo", "Corrente com crucifixo e óculos"]',
'As listras verdes gritam anos 90 e o caramelo do tênis aquece — a meia franzida é o detalhe de quem sabe.',
'["Tênis branco para versão neutra", "Camiseta listrada comum se não achar a polo"]'),
('Jersey 42 & Sweat Jorts', 'Basquete vintage com conforto atual.', 'evento-casual', 'vintage', 'calor', 'intermediario', 'azul', '/estilos/vintage/18.jpg',
'["Jersey de basquete azul-claro sobre camiseta creme", "Jorts de moletom cinza abaixo do joelho", "Air Force 1 preto com cadarço amarelo", "Corrente dourada e relógio branco"]',
'Jersey sobre camiseta é o layering Y2K essencial — o cadarço amarelo repete os detalhes do jersey.',
'["AF1 branco para simplificar", "Bermuda jeans no lugar do moletom"]'),
('Vermelho & Digi-Camo', 'Contraste dos anos 2000 sem medo.', 'dia-a-dia', 'vintage', 'meia-estacao', 'avancado', 'vinho', '/estilos/vintage/19.jpg',
'["Hoodie vermelho cropped com letras", "Jorts camuflado digital cinza volumoso", "Cinto de ilhós com corrente", "Meião branco", "Tênis de skate preto e branco"]',
'Vermelho sobre digi-camo é ousadia calculada: o cinza do camo é neutro, então só há uma cor de verdade no look.',
'["Hoodie cinza para versão discreta", "Calça camo no frio"]'),
('Preto Harlem', 'Referência direta do hip-hop dos 2000.', 'evento-casual', 'vintage', 'calor', 'avancado', 'preto', '/estilos/vintage/20.jpg',
'["Camiseta preta com gráfico gótico", "Bermuda jeans preta de barra desfiada", "Bandana amarrada na cabeça", "Correntes douradas grossas", "Tênis de corrida vintage surrado"]',
'O preto total com ouro e bandana é o código Harlem revivido — o tênis destruído é proposital, não descuido.',
'["Boné no lugar da bandana", "Tênis limpo para versão social"]'),
('Flanela & Cargo Gigante', 'Proporções raras de arquivo.', 'dia-a-dia', 'vintage', 'meia-estacao', 'avancado', 'bege', '/estilos/vintage/21.jpg',
'["Overshirt xadrez vermelha cropped", "Cargo creme supervolumosa com bolso de rádio", "Cinto preto", "Sapato preto discreto"]',
'Jaqueta curta + calça gigante é o contraste de proporção Y2K de passarela — o xadrez vermelho dá o tom retrô.',
'["Cargo bege comum se o volume assustar", "Camiseta branca por baixo aparecendo"]'),
('Polo Xadrez & Timberland', 'Y2K com pegada de trabalho.', 'dia-a-dia', 'vintage', 'meia-estacao', 'intermediario', 'bege', '/estilos/vintage/22.jpg',
'["Polo xadrez azul com gola navy", "Camada listrada aparecendo na barra", "Cargo cáqui baggy", "Bota amarela tipo Timberland", "Boné marrom SD"]',
'O xadrez da polo e a Timberland são a dupla exata dos anos 2000 — a camada listrada na barra soma profundidade.',
'["Tênis branco para leveza", "Polo lisa se o xadrez cansar"]'),
('Big Pony Rosa', 'Polo statement com denim destruído.', 'faculdade', 'vintage', 'calor', 'facil', 'azul', '/estilos/vintage/23.jpg',
'["Polo rosa com big pony bordado", "Baggy jeans claro rasgado", "Bota ou clog caramelo", "Corrente dourada", "Boné estampado para trás"]',
'Rosa sobre denim claro é a fórmula 2000s do campus americano — a bota caramelo repete o tom quente da polo.',
'["Polo branca para versão neutra", "Tênis retrô no lugar da bota"]'),
('Created to Create', 'Branco total com jorts destruído.', 'dia-a-dia', 'vintage', 'calor', 'facil', 'branco', '/estilos/vintage/24.jpg',
'["Camiseta branca boxy com frase", "Jorts claro destroyed", "Tênis chunky de cadarço grosso", "Meia branca e corrente prata"]',
'Branco sobre denim claro deixa o tênis statement como única peça de peso — verão Y2K sem esforço.',
'["Tênis branco comum para simplificar", "Camiseta gráfica para mais personalidade"]'),
('Jersey de Tela 80', 'Futebol americano vintage em preto.', 'noite', 'vintage', 'calor', 'intermediario', 'preto', '/estilos/vintage/25.jpg',
'["Jersey de tela preto (nº 80) sobre camiseta branca", "Jorts preto de lavagem ácida", "adidas Samba preto", "Corrente prata e chaveiro no cós", "Bolsa matelassê preta"]',
'Preto sobre preto com texturas diferentes (tela + denim ácido) — o branco por baixo desenha o jersey.',
'["Jersey colorido para versão vibrante", "Calça baggy preta à noite fria"]'),
('Flanela & Jorts Índigo', 'Xadrez azul com denim cru.', 'faculdade', 'vintage', 'meia-estacao', 'intermediario', 'azul', '/estilos/vintage/26.jpg',
'["Camisa flanela xadrez azul", "Jorts índigo escuro amplo", "Cinto de gorgurão off-white", "adidas Superstar com listras verdes", "Boné azul LA e meia branca"]',
'Tudo azul em três lavagens diferentes — o cinto claro e as listras verdes do tênis são os respiros da paleta.',
'["Camiseta branca sob a flanela aberta", "Jeans baggy no frio"]'),
('Denim Escuro & Off-White', 'Work jacket com alfaiataria clara.', 'evento-casual', 'workwear', 'meia-estacao', 'intermediario', 'branco', '/estilos/workwear/11.jpg',
'["Jaqueta de trabalho em denim escuro", "Bandana no pescoço", "Calça off-white ampla de pregas", "Sapato preto de sola tratorada", "Trucker cap branco e vermelho"]',
'O denim cru sobre off-white é o workwear em versão elegante — a bandana é o acento de heritage.',
'["Sem bandana para versão sóbria", "Jeans reto cru no lugar da calça clara"]'),
('Colete de Lona', 'Peça de trabalho como statement.', 'dia-a-dia', 'workwear', 'meia-estacao', 'intermediario', 'marrom', '/estilos/workwear/12.jpg',
'["Colete de lona marrom (duck canvas)", "Camiseta branca oversized", "Carpenter pants cinza lavada", "Clog ou Birkenstock de camurça", "Boné creme"]',
'O colete de lona no lugar da jaqueta é a escolha rara que define o look — tons terrosos do workwear clássico.',
'["Jaqueta de lona no frio", "Bota de trabalho no lugar do clog"]'),
('Trucker & Balloon Bege', 'Denim vintage com volume atual.', 'dia-a-dia', 'workwear', 'meia-estacao', 'intermediario', 'bege', '/estilos/workwear/13.jpg',
'["Jaqueta trucker azul com bolso de aba", "Regata branca", "Chino bege balloon de pregas", "Mocassim ou clog de camurça caramelo", "Boné vermelho e óculos escuros"]',
'A trucker vintage sobre o chino balloon mistura décadas — o boné vermelho é o ponto de cor à la Marlboro.',
'["Camiseta no lugar da regata", "Bota de couro para o entardecer"]'),
('Micro-Xadrez & Chino', 'Workwear limpo para o escritório.', 'trabalho', 'workwear', 'calor', 'facil', 'bege', '/estilos/workwear/14.jpg',
'["Camisa de manga curta micro-xadrez vinho", "Chino bege de corte amplo", "Cinto preto com mosquetão", "Penny loafer preto"]',
'O micro-xadrez lê como textura de longe — camisa dentro da calça e loafer fazem a ponte com o formal.',
'["Camisa para fora em happy hour", "Tênis branco na sexta casual"]'),
('Flanela Marrom & Timberland', 'O clássico de outono americano.', 'dia-a-dia', 'workwear', 'frio', 'facil', 'marrom', '/estilos/workwear/15.jpg',
'["Overshirt de flanela xadrez marrom", "Camiseta branca por baixo", "Baggy jeans escuro", "Bota amarela tipo Timberland", "Boné caramelo New Era"]',
'Flanela marrom + Timberland é o uniforme workwear de frio que nunca erra — o boné repete o caramelo da bota.',
'["Fechar a flanela como camisa", "Moletom por baixo no frio forte"]'),
('Colete de Lã & Botas', 'Heritage em camadas de inverno.', 'evento-casual', 'workwear', 'frio', 'avancado', 'azul', '/estilos/workwear/16.jpg',
'["Colete de lã grafite", "Camisa listrada verde e branca", "Henley branca na base", "Jeans índigo com barra dobrada larga", "Botas de hiking e boné navy"]',
'Três camadas com texturas diferentes (lã, algodão listrado, denim cru) — profundidade sem nenhuma peça gritar.',
'["Remover o colete em ambiente aquecido", "Trocar bota de hiking por bota de trabalho"]'),
('Work Jacket Taupe', 'Workwear noturno com alfaiataria.', 'noite', 'workwear', 'meia-estacao', 'intermediario', 'marrom', '/estilos/workwear/17.jpg',
'["Jaqueta de trabalho taupe de zíper", "Regata canelada branca", "Calça preta ampla de pregas", "Loafer preto de sola tratorada", "Boné preto e cinto de fivela prata"]',
'A work jacket sobre calça de alfaiataria é a mistura workwear + noite — o taupe aquece o preto.',
'["Camiseta no lugar da regata", "Bota preta na chuva"]'),
('Detroit Preta & Carpenter', 'Carhartt de inverno da cabeça aos pés.', 'dia-a-dia', 'workwear', 'frio', 'intermediario', 'preto', '/estilos/workwear/18.jpg',
'["Jaqueta Detroit preta de lona", "Carpenter pants marrom-escura", "Cinto preto de couro", "Bota amarela tipo Timberland", "Gorro preto e óculos escuros"]',
'Preto + marrom + bota caramelo: a tríade workwear de inverno. A lona da jaqueta ganha caráter com o uso.',
'["Hoodie por baixo no frio pesado", "Bota preta para look mais fechado"]'),
('Conjunto Raw Denim', 'Denim cru dos pés à cabeça.', 'evento-casual', 'workwear', 'meia-estacao', 'avancado', 'azul', '/estilos/workwear/19.jpg',
'["Jaqueta harrington de denim cru", "Jorts de pregas no mesmo denim (conjunto)", "Polo branca por baixo", "Meião branco", "Loafer vinho de sola alta e boné navy"]',
'O conjunto de raw denim com pregas trata o jeans como alfaiataria — o loafer vinho confirma a intenção.',
'["Separar jaqueta e jorts em looks distintos", "Tênis branco para versão casual"]');
