-- =============================================================
-- Lookbook expandido: +87 combinações, uma por foto de referência,
-- com clima, cor base e peças coerentes com a imagem.
-- Também corrige fotos com clima incoerente em looks existentes.
-- =============================================================

-- Correções de coerência (foto x clima)
update public.looks set image_url = '/estilos/casual/10.jpg'   where title = 'Evento Casual de Verão';
update public.looks set image_url = '/estilos/gorpcore/03.jpg' where title = 'Minimalista de Inverno';

insert into public.looks (title, description, occasion, style, climate, level, base_color, image_url, pieces, why_it_works, adaptations) values
('Zip Terroso', 'Dia a dia urbano com tons de terra.', 'dia-a-dia', 'casual', 'meia-estacao', 'intermediario', 'marrom', '/estilos/casual/03.jpg',
'["Jaqueta de zíper marrom", "Camiseta neutra por baixo", "Calça reta preta", "Calçado escuro limpo"]',
'O marrom sobre base preta aquece o visual sem perder a sobriedade. A jaqueta de zíper é a terceira peça que organiza o look.',
'["Trocar calça preta por bege para um look tonal", "Trocar jaqueta por overshirt no calor"]'),
('Couro & Denim Claro', 'Noite casual com contraste forte.', 'noite', 'casual', 'meia-estacao', 'intermediario', 'branco', '/estilos/casual/05.jpg',
'["Jaqueta de couro preta", "Camiseta escura", "Jeans claro de corte amplo", "Tênis ou bota preta"]',
'O contraste entre o couro preto e o denim claro cria presença imediata — o volume da calça moderniza o clássico da jaqueta.',
'["Trocar jeans claro por preto para all black", "Trocar bota por tênis branco"]'),
('Trucker Clássico', 'O básico atemporal do denim.', 'dia-a-dia', 'casual', 'meia-estacao', 'facil', 'azul', '/estilos/casual/07.jpg',
'["Jaqueta jeans (trucker)", "Regata ou camiseta branca", "Jeans escuro de lavagem diferente", "Calçado escuro"]',
'Denim com denim funciona quando as lavagens são bem diferentes. O branco no meio separa as camadas e ilumina o look.',
'["Trocar regata por camiseta lisa", "Trocar jeans escuro por calça preta"]'),
('Couro Noturno Marrom', 'Jantar ou bar com sofisticação quente.', 'noite', 'casual', 'meia-estacao', 'avancado', 'marrom', '/estilos/casual/09.jpg',
'["Jaqueta de couro", "Camiseta ou tricô fino escuro", "Calça marrom de alfaiataria casual", "Sapato ou bota de couro"]',
'Couro com marrom é a versão mais quente e rara do look de noite — foge do all black mantendo a mesma força.',
'["Trocar calça marrom por grafite", "Adicionar relógio de couro"]'),
('Conjunto Terroso', 'Evento casual com cara de editorial.', 'evento-casual', 'casual', 'meia-estacao', 'avancado', 'marrom', '/estilos/casual/02.jpg',
'["Jaqueta e calça em tom de chocolate", "Camiseta bege por baixo", "Tênis neutro", "Bolsa ou acessório de couro"]',
'Conjunto monocromático em tons de terra transmite intenção máxima — o bege no meio quebra o bloco único e dá profundidade.',
'["Separar as peças do conjunto em outros looks", "Trocar tênis por bota para a noite"]'),
('Camo de Verão', 'Rolê de dia com atitude militar.', 'dia-a-dia', 'streetwear', 'calor', 'facil', 'verde', '/estilos/streetwear/01.jpg',
'["Camiseta branca lisa", "Bermuda camuflada de corte amplo", "Tênis branco", "Boné"]',
'A camuflagem entra como única peça de destaque sobre base branca — padrão forte pede o resto do look limpo.',
'["Trocar bermuda camo por jorts", "Adicionar meia branca aparente"]'),
('Jersey Urbano', 'Camisa de time fora do estádio.', 'dia-a-dia', 'streetwear', 'calor', 'facil', 'cinza', '/estilos/streetwear/02.jpg',
'["Football jersey", "Calça baggy preta", "Bota ou tênis robusto", "Óculos escuros"]',
'O jersey vira peça de estilo quando ancorado em baixo volumoso e escuro — referência direta do street dos anos 2000.',
'["Trocar baggy por jorts no calor extremo", "Usar jersey vintage de time clássico"]'),
('Futebol Retrô', 'O jersey brasileiro como statement.', 'evento-casual', 'streetwear', 'calor', 'intermediario', 'verde', '/estilos/streetwear/03.jpg',
'["Jersey retrô de seleção", "Bermuda cargo camuflada", "Tênis de corrida", "Meia aparente"]',
'Duas peças fortes (jersey + camo) funcionam porque dividem a mesma família de cores — verde e amarelo sobre neutros.',
'["Trocar camo por jorts preto para simplificar", "Versão com jersey azul e cargo bege"]'),
('Puffer com Denim Claro', 'Frio urbano com volume proposital.', 'dia-a-dia', 'streetwear', 'frio', 'intermediario', 'branco', '/estilos/streetwear/04.jpg',
'["Jaqueta puffer com capuz", "Jeans baggy claro", "Bota de trabalho clara", "Camadas por baixo"]',
'O puffer dá o volume em cima e o baggy equilibra embaixo — a paleta clara diferencia dos looks de frio óbvios.',
'["Trocar puffer por bomber em frio moderado", "Escurecer o jeans para look noturno"]'),
('Ringer Esportiva', 'Faculdade com referência retrô-esportiva.', 'faculdade', 'streetwear', 'calor', 'facil', 'branco', '/estilos/streetwear/06.jpg',
'["Camiseta polo listrada esportiva", "Jeans baggy claro", "Tênis branco", "Acessório discreto"]',
'As listras esportivas dão personalidade a uma base simples de verão — fácil de copiar e difícil de errar.',
'["Trocar jeans por bermuda de sarja", "Adicionar boné para o sol"]'),
('Jorts Gráfico', 'Verão urbano com camiseta de estampa.', 'dia-a-dia', 'streetwear', 'calor', 'facil', 'preto', '/estilos/streetwear/08.jpg',
'["Camiseta branca com gráfico", "Jorts preto", "Tênis retrô", "Corrente prata"]',
'A fórmula jorts + camiseta gráfica é o uniforme do verão street — o contraste preto e branco mantém tudo coeso.',
'["Trocar gráfico por camiseta lisa", "Trocar tênis retrô por chunky"]'),
('Rugby & Jorts', 'Streetwear com toque colegial.', 'faculdade', 'streetwear', 'calor', 'intermediario', 'azul', '/estilos/streetwear/09.jpg',
'["Polo rugby listrada", "Jorts escuro", "Tênis branco robusto", "Boné e corrente"]',
'A rugby listrada encontra o jorts: mistura de preppy com street que funciona pela paleta fechada em azul e branco.',
'["Trocar jorts por baggy jeans", "Tirar o boné para versão mais limpa"]'),
('Rugby Noturno', 'Noite casual com peça de colarinho.', 'noite', 'streetwear', 'meia-estacao', 'facil', 'azul', '/estilos/streetwear/10.jpg',
'["Camisa rugby navy", "Jeans escuro amplo", "Bota ou tênis robusto", "Relógio discreto"]',
'O colarinho da rugby arruma o look sem perder o DNA street — navy sobre denim escuro é presença garantida à noite.',
'["Trocar rugby por moletom de gola careca", "Clarear o jeans para o dia"]'),
('Denim & Moletom', 'Frio urbano com camadas de trabalho.', 'dia-a-dia', 'workwear', 'frio', 'facil', 'preto', '/estilos/workwear/01.jpg',
'["Jaqueta trucker escura", "Moletom com capuz cinza", "Jeans preto amplo", "Bota de trabalho clara"]',
'Moletom por baixo da trucker é a camada workwear clássica — a bota clara quebra o bloco escuro e dá o toque de ofício.',
'["Trocar bota por tênis robusto", "Adicionar gorro no frio intenso"]'),
('Double Denim Preto', 'All black de trabalho com textura.', 'dia-a-dia', 'workwear', 'meia-estacao', 'avancado', 'preto', '/estilos/workwear/02.jpg',
'["Jaqueta jeans preta", "Calça jeans preta ampla", "Camiseta escura", "Boné preto"]',
'Denim sobre denim na mesma cor exige texturas visíveis — o desgaste natural do tecido faz o trabalho de diferenciação.',
'["Quebrar com camiseta branca", "Trocar boné por gorro"]'),
('Meio-Zíper de Ofício', 'Trabalho com robustez discreta.', 'trabalho', 'workwear', 'frio', 'intermediario', 'azul', '/estilos/workwear/03.jpg',
'["Tricô navy de meio-zíper", "Camisa por baixo", "Calça de sarja escura", "Bota ou sapato robusto"]',
'O meio-zíper com colarinho aparecendo une o formal e o funcional — azul profundo transmite confiança sem esforço.',
'["Tirar a camisa para versão casual", "Trocar sarja por jeans escuro"]'),
('Chore Jacket', 'A jaqueta de ofício francesa.', 'dia-a-dia', 'workwear', 'meia-estacao', 'intermediario', 'bege', '/estilos/workwear/04.jpg',
'["Chore jacket preta", "Camiseta branca", "Calça ampla bege", "Bota ou sapato de couro"]',
'A chore jacket é a terceira peça original do workwear — o contraste preto sobre bege equilibra peso e leveza.',
'["Trocar calça bege por jeans cru", "Enrolar a barra para mostrar a bota"]'),
('Workwear Marrom', 'Frio com tons de couro e terra.', 'dia-a-dia', 'workwear', 'frio', 'intermediario', 'marrom', '/estilos/workwear/05.jpg',
'["Jaqueta workwear marrom", "Capuz cinza por baixo", "Jeans escuro amplo", "Bota de couro"]',
'Marrom + cinza + denim é o trio de trabalho clássico: rústico, funcional e cheio de textura.',
'["Trocar capuz por gola alta", "Versão com calça de sarja verde-oliva"]'),
('Tonal Cru', 'Workwear limpo em tons de areia.', 'dia-a-dia', 'workwear', 'meia-estacao', 'facil', 'bege', '/estilos/workwear/06.jpg',
'["Moletom cru de gola careca", "Calça ampla no mesmo tom", "Calçado escuro para ancorar", "Acessório mínimo"]',
'O monocromático cru é o workwear em versão suave — o calçado escuro impede que o look flutue.',
'["Adicionar chore jacket em cima", "Trocar calçado escuro por bota caramelo"]'),
('Sherpa & Denim', 'Frio com a clássica jaqueta forrada.', 'dia-a-dia', 'workwear', 'frio', 'intermediario', 'azul', '/estilos/workwear/07.jpg',
'["Jaqueta jeans com forro sherpa", "Camiseta ou moletom claro", "Jeans claro amplo", "Bota de trabalho"]',
'O forro de lã aparente é o detalhe que transforma a trucker em peça de inverno — lavagens claras mantêm o look leve.',
'["Fechar a jaqueta em dias gelados", "Trocar bota por tênis robusto"]'),
('Fleece & Cargo', 'Utilitário de frio urbano.', 'dia-a-dia', 'workwear', 'frio', 'facil', 'preto', '/estilos/workwear/08.jpg',
'["Fleece preto", "Calça cargo preta", "Bota de trabalho caramelo", "Acessórios pretos"]',
'All black utilitário com um único ponto de cor: a bota caramelo. É o detalhe que faz o look inteiro parecer pensado.',
'["Trocar fleece por moletom pesado", "Adicionar gorro preto"]'),
('Couro de Ofício', 'Noite com jaqueta de couro cinza.', 'noite', 'workwear', 'meia-estacao', 'avancado', 'cinza', '/estilos/workwear/09.jpg',
'["Jaqueta de couro cinza", "Camisa com gravata fina", "Calça de alfaiataria grafite", "Sapato robusto"]',
'Couro com alfaiataria é a fronteira entre o workwear e o formal — a paleta cinza única amarra a mistura.',
'["Tirar a gravata para versão casual", "Trocar sapato por bota preta"]'),
('Polo Preta Total', 'Evento casual com o mínimo perfeito.', 'evento-casual', 'smartcasual', 'meia-estacao', 'facil', 'preto', '/estilos/smartcasual/02.jpg',
'["Polo de malha preta", "Calça de alfaiataria preta", "Sapato ou bota escura", "Relógio discreto"]',
'Polo de malha com alfaiataria é o smart casual em estado puro — o preto total entrega elegância sem uma peça formal sequer.',
'["Trocar preto por navy total", "Adicionar blazer para eventos noturnos"]'),
('Jaqueta Off-White', 'Noite com contraste invertido.', 'noite', 'smartcasual', 'meia-estacao', 'avancado', 'branco', '/estilos/smartcasual/03.jpg',
'["Jaqueta off-white ou creme", "Regata ou camiseta branca", "Calça escura ampla", "Sapato de couro escuro"]',
'Inverter o esperado — claro em cima, escuro embaixo à noite — cria sofisticação instantânea. Poucos fazem; por isso funciona.',
'["Trocar regata por camiseta lisa", "Versão de dia com tênis branco"]'),
('Camurça & Tricô', 'Trabalho de inverno com textura nobre.', 'trabalho', 'smartcasual', 'frio', 'avancado', 'marrom', '/estilos/smartcasual/04.jpg',
'["Jaqueta de camurça marrom", "Tricô creme por baixo", "Calça de alfaiataria escura", "Sapato de couro"]',
'Camurça sobre tricô empilha duas texturas quentes — o contraste com a calça escura estrutura o visual para o trabalho.',
'["Trocar camurça por blazer de lã", "Versão com gola alta preta"]'),
('Tricô Verde', 'Cor avançada no ambiente de trabalho.', 'trabalho', 'smartcasual', 'frio', 'intermediario', 'verde', '/estilos/smartcasual/08.jpg',
'["Tricô verde-oliva", "Calça de alfaiataria grafite", "Sapato ou bota preta", "Cinto preto"]',
'Verde fechado com grafite é a forma mais segura de sair dos neutros no trabalho — sóbrio, mas com personalidade.',
'["Camisa branca por baixo do tricô", "Trocar verde por vinho"]'),
('Cardigan Bege', 'Date de frio com aconchego elegante.', 'date', 'smartcasual', 'frio', 'facil', 'bege', '/estilos/smartcasual/09.jpg',
'["Cardigan ou tricô bege", "Camiseta escura por baixo", "Calça escura", "Calçado de couro"]',
'Tons quentes transmitem proximidade — a peça de tricô bege sobre base escura é acessível e sofisticada ao mesmo tempo.',
'["Trocar cardigan por overshirt de lã", "Versão clara com calça cinza"]'),
('Overshirt & Branco', 'Contraste limpo para eventos de dia.', 'evento-casual', 'smartcasual', 'meia-estacao', 'intermediario', 'marrom', '/estilos/smartcasual/10.jpg',
'["Overshirt marrom", "Camiseta branca", "Calça branca ou cru ampla", "Tênis limpo"]',
'Calça clara com overshirt escura inverte a fórmula comum e alonga a silhueta — combinação de quem já domina os neutros.',
'["Trocar calça branca por bege", "Fechar a overshirt como camisa"]'),
('Polo Areia', 'Fim de tarde com elegância mediterrânea.', 'evento-casual', 'oldmoney', 'meia-estacao', 'facil', 'bege', '/estilos/oldmoney/01.jpg',
'["Polo de malha areia", "Calça de alfaiataria marrom", "Mocassim ou sapato de couro", "Óculos clássicos"]',
'Areia sobre marrom é o gradiente old money por excelência — nada compete, tudo conversa.',
'["Trocar polo por camisa de linho", "Versão de verão com calça cru"]'),
('Navy & Cru a Cavalo', 'O clássico equestre urbano.', 'evento-casual', 'oldmoney', 'meia-estacao', 'avancado', 'azul', '/estilos/oldmoney/03.jpg',
'["Jaqueta navy estruturada", "Camisa clara", "Calça cru ampla", "Sapato de couro escuro"]',
'Navy sobre cru com camisa aparecendo é herança direta do guarda-roupa aristocrático — atemporal e impossível de datar.',
'["Trocar jaqueta por blazer", "Versão com tricô sobre a camisa"]'),
('Suéter Vinho', 'Trabalho de frio com cor nobre.', 'trabalho', 'oldmoney', 'frio', 'intermediario', 'vinho', '/estilos/oldmoney/05.jpg',
'["Suéter vinho sobre camisa branca", "Calça de alfaiataria clara", "Sapato de couro marrom", "Relógio de couro"]',
'O vinho sobre colarinho branco é o código old money para o inverno — cor profunda, base clássica.',
'["Trocar calça clara por grafite", "Versão com suéter verde-garrafa"]'),
('Cardigan Navy', 'O clássico do avô, usado certo.', 'trabalho', 'oldmoney', 'meia-estacao', 'intermediario', 'azul', '/estilos/oldmoney/06.jpg',
'["Cardigan navy", "Camisa branca", "Calça marrom ou caramelo", "Sapato de couro"]',
'Cardigan com camisa é sofisticação silenciosa — o navy com marrom é o pareamento mais elegante dos clássicos.',
'["Trocar cardigan por suéter de gola V", "Versão sem camisa com camiseta branca premium"]'),
('Zip Bordô', 'Date de inverno com profundidade.', 'date', 'oldmoney', 'frio', 'avancado', 'vinho', '/estilos/oldmoney/07.jpg',
'["Cardigan de zíper bordô", "Camiseta ou camisa escura", "Calça de alfaiataria cinza", "Sapato de couro escuro"]',
'Bordô com cinza é raro e memorável — transmite calma e presença na medida certa para um encontro.',
'["Trocar bordô por caramelo", "Adicionar sobretudo em frio intenso"]'),
('Cardigan Verde', 'Encontro de frio com tom de biblioteca.', 'date', 'oldmoney', 'frio', 'intermediario', 'verde', '/estilos/oldmoney/08.jpg',
'["Cardigan verde-garrafa", "Camiseta ou camisa neutra", "Calça de alfaiataria marrom", "Sapato de couro"]',
'Verde-garrafa com marrom é a paleta das bibliotecas inglesas — intelectual, quente e fora do óbvio.',
'["Trocar cardigan por tricô de gola redonda", "Versão com calça cinza"]'),
('Polo Creme Noturna', 'Noite elegante sem blazer.', 'noite', 'oldmoney', 'meia-estacao', 'facil', 'branco', '/estilos/oldmoney/09.jpg',
'["Polo de malha creme", "Calça de alfaiataria preta", "Sapato de couro preto", "Relógio discreto"]',
'Creme sobre preto à noite é o contraste mais limpo que existe — a malha da polo faz o papel de peça nobre.',
'["Trocar polo por tricô fino", "Adicionar sobretudo no frio"]'),
('Navy Total', 'Verão com uma cor só.', 'evento-casual', 'oldmoney', 'calor', 'intermediario', 'azul', '/estilos/oldmoney/10.jpg',
'["Polo navy", "Calça de alfaiataria navy", "Mocassim de couro escuro", "Óculos clássicos"]',
'O monocromático navy é o segredo do verão elegante — mais interessante que preto, mais sóbrio que qualquer estampa.',
'["Quebrar com cinto e sapato caramelo", "Versão com bermuda de alfaiataria"]'),
('Polo Romana', 'Viagem com café e monumentos.', 'viagem', 'oldmoney', 'calor', 'facil', 'marrom', '/estilos/oldmoney/11.jpg',
'["Polo de malha marrom", "Chino cru ou areia", "Sapato de couro ou mocassim", "Relógio de couro"]',
'Marrom com areia é conforto visual — perfeito para caminhar por uma cidade histórica sem parecer turista.',
'["Trocar chino por alfaiataria leve", "Adicionar camisa aberta sobre a polo"]'),
('Malha Taupe', 'Trabalho tranquilo em tons neutros.', 'trabalho', 'oldmoney', 'meia-estacao', 'facil', 'bege', '/estilos/oldmoney/12.jpg',
'["Polo de malha taupe", "Calça de alfaiataria marrom", "Sapato de couro escuro", "Cinto combinando"]',
'Taupe é o neutro mais subestimado — entre o cinza e o bege, combina com toda a paleta quente sem esforço.',
'["Trocar calça por cinza para esfriar a paleta", "Versão com camisa branca por baixo"]'),
('Rugby Clássico', 'O uniforme universitário original.', 'faculdade', 'preppy', 'meia-estacao', 'facil', 'azul', '/estilos/preppy/01.jpg',
'["Camisa rugby listrada navy", "Chino cru", "Tênis ou mocassim", "Boné neutro"]',
'A rugby com chino claro é o preppy fundamental — colegial sem infantilidade, casual sem desleixo.',
'["Trocar chino por jeans claro", "Versão com suéter nos ombros"]'),
('Listras P&B', 'Evento casual com gráfico clássico.', 'evento-casual', 'preppy', 'meia-estacao', 'intermediario', 'preto', '/estilos/preppy/03.jpg',
'["Suéter de listras largas preto e branco", "Calça branca ou cru", "Tênis limpo", "Boné escuro"]',
'Listras largas em preto e branco são gráficas sem serem estampas — com base clara, o suéter é a estrela.',
'["Trocar calça clara por jeans", "Versão de verão com camiseta listrada"]'),
('Rugby & Alfaiataria', 'Colegial elevado para o dia a dia.', 'faculdade', 'preppy', 'meia-estacao', 'intermediario', 'azul', '/estilos/preppy/04.jpg',
'["Rugby listrada navy e branca", "Calça de alfaiataria cinza", "Tênis branco", "Meia discreta"]',
'Trocar o chino pela alfaiataria eleva a rugby — o cinza esfria a paleta e tira o look do casual óbvio.',
'["Voltar ao chino para versão clássica", "Adicionar jaqueta harrington"]'),
('Marinheiro', 'Verão com listras navais.', 'viagem', 'preppy', 'calor', 'facil', 'azul', '/estilos/preppy/05.jpg',
'["Camiseta listrada navy e branca", "Calça branca ou cru", "Tênis ou alpargata", "Óculos de sol"]',
'As listras bretãs com branco total são a fórmula de verão mais antiga que existe — e continua imbatível.',
'["Trocar calça por bermuda de sarja", "Adicionar camisa de linho aberta"]'),
('Polo Listrado de Verão', 'Evento de dia com frescor clássico.', 'evento-casual', 'preppy', 'calor', 'facil', 'branco', '/estilos/preppy/06.jpg',
'["Polo de malha listrada", "Calça branca leve", "Mocassim ou tênis limpo", "Relógio de couro"]',
'Malha listrada sobre branco é elegância de clube náutico — leve, arrumado e fotogênico.',
'["Trocar calça branca por bege", "Versão com bermuda alinhada"]'),
('Ivy League', 'Trabalho com herança universitária.', 'trabalho', 'preppy', 'meia-estacao', 'avancado', 'bege', '/estilos/preppy/07.jpg',
'["Polo listrada de malha", "Gravata de malha", "Calça de alfaiataria com pregas", "Sapato de couro"]',
'Gravata com polo é o truque Ivy League original — formal no código, relaxado na execução.',
'["Tirar a gravata para descontrair", "Trocar polo por camisa oxford"]'),
('Paris Preppy', 'Viagem urbana com listras e denim.', 'viagem', 'preppy', 'meia-estacao', 'facil', 'azul', '/estilos/preppy/08.jpg',
'["Rugby listrada", "Jeans claro reto", "Tênis branco", "Boné"]',
'Rugby com jeans claro é o preppy de férias — confortável para andar o dia inteiro e bonito em qualquer foto.',
'["Trocar jeans por chino", "Adicionar cardigan nos ombros"]'),
('Suéter Listrado', 'Frio de campus com charme.', 'faculdade', 'preppy', 'frio', 'facil', 'azul', '/estilos/preppy/09.jpg',
'["Suéter listrado azul", "Jeans de lavagem média", "Tênis retrô", "Camisa por baixo opcional"]',
'Suéter de listras com denim é o inverno universitário clássico — fácil, quente e com personalidade.',
'["Adicionar colarinho branco aparecendo", "Trocar jeans por calça de sarja"]'),
('Rugby Verde', 'Campus com paleta fora do óbvio.', 'faculdade', 'preppy', 'meia-estacao', 'facil', 'verde', '/estilos/preppy/10.jpg',
'["Rugby verde e branca", "Calça cru ou branca", "Tênis limpo", "Meia discreta"]',
'O verde tira a rugby do lugar-comum navy — com base clara, o look fica fresco e memorável.',
'["Trocar calça clara por jeans", "Versão com bermuda no calor"]'),
('Navy & Cru Minimal', 'Dia limpo com dois tons.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'azul', '/estilos/minimalista/01.jpg',
'["Camiseta navy de tecido bom", "Calça cru ampla", "Tênis branco", "Sem acessórios"]',
'Navy sobre cru é o duo minimalista mais quente — contraste suave, zero esforço aparente.',
'["Inverter: camiseta cru + calça navy", "Adicionar relógio de aço"]'),
('Verde Suave', 'Verão minimalista com cor.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'verde', '/estilos/minimalista/02.jpg',
'["Camiseta verde-oliva", "Calça branca ou cru", "Tênis neutro", "Boné verde opcional"]',
'O verde-oliva funciona como neutro — sobre branco, dá cor ao look sem quebrar a estética limpa.',
'["Trocar verde por terracota", "Versão com bermuda de sarja"]'),
('Branco & Cinza Lavado', 'Básico com denim de personalidade.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'branco', '/estilos/minimalista/04.jpg',
'["Camiseta branca", "Jeans cinza lavado amplo", "Tênis ou bota clara", "Boné de cor como acento"]',
'A lavagem acinzentada do denim faz o papel de textura — o boné é o único ponto de cor e basta.',
'["Tirar o boné para versão mais limpa", "Trocar jeans por preto"]'),
('Preto & Areia', 'Contraste seco de verão.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'preto', '/estilos/minimalista/05.jpg',
'["Camiseta preta", "Calça cargo cru ou areia", "Tênis neutro", "Acessório mínimo"]',
'Preto sobre areia é o contraste minimalista com temperatura — a cargo dá utilidade sem ruído visual.',
'["Trocar cargo por calça reta", "Versão invertida: cru em cima, preto embaixo"]'),
('Branco & Denim Claro', 'O verão em estado puro.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'branco', '/estilos/minimalista/06.jpg',
'["Camiseta branca de peso bom", "Jeans claro reto", "Sapato ou tênis escuro", "Bolsa transversal opcional"]',
'Branco com denim claro é luz total — o calçado escuro ancora e impede o look de desaparecer.',
'["Trocar calçado escuro por branco", "Adicionar camisa aberta"]'),
('Cinza Claro Total', 'Monocromático de verão.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'cinza', '/estilos/minimalista/07.jpg',
'["Camiseta branca ou cinza-claro", "Calça cinza-clara ampla", "Tênis neutro", "Sem estampas"]',
'Tons de cinza claro empilhados criam um look etéreo — a variação sutil entre as peças é o próprio design.',
'["Ancorar com calçado escuro", "Versão com bermuda alinhada"]'),
('Preto Fluido', 'Noite de calor com volume.', 'noite', 'minimalista', 'calor', 'facil', 'preto', '/estilos/minimalista/08.jpg',
'["Camiseta preta", "Calça preta ampla e fluida", "Sapato ou tênis preto", "Relógio discreto"]',
'All black de verão pede tecidos leves e caimento fluido — presença máxima sem passar calor.',
'["Trocar camiseta por polo de malha", "Versão com sandália de couro premium"]'),
('Preto com Cinto', 'O detalhe que estrutura.', 'noite', 'minimalista', 'calor', 'intermediario', 'preto', '/estilos/minimalista/09.jpg',
'["Camiseta preta para dentro da calça", "Calça preta de alfaiataria", "Cinto preto discreto", "Sapato escuro"]',
'Camiseta para dentro com cinto aparente transforma o básico em intencional — um gesto, outro nível.',
'["Soltar a camiseta para descontrair", "Trocar sapato por tênis minimalista"]'),
('Grafite Urbano', 'Cidade em tons de carvão.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'cinza', '/estilos/minimalista/11.jpg',
'["Camiseta preta", "Calça grafite ampla", "Tênis escuro", "Acessório mínimo"]',
'Preto sobre grafite é o quase-monocromático que sempre funciona — profundidade sem contraste duro.',
'["Clarear com tênis branco", "Versão com camiseta cinza mescla"]'),
('Boxy & Cinza', 'Campus com silhueta quadrada.', 'faculdade', 'minimalista', 'calor', 'facil', 'cinza', '/estilos/minimalista/13.jpg',
'["Boxy tee branca", "Jeans cinza lavado", "Tênis preto ou branco", "Boné opcional"]',
'O corte quadrado da boxy dá atitude ao básico — com denim lavado, o look fica moderno sem tentar demais.',
'["Trocar boxy por oversized comum", "Escurecer o jeans à noite"]'),
('Cinza Espelhado', 'Transição de estação em cinza.', 'dia-a-dia', 'minimalista', 'meia-estacao', 'facil', 'cinza', '/estilos/minimalista/14.jpg',
'["Camiseta preta", "Calça cinza ampla de alfaiataria", "Tênis limpo", "Relógio discreto"]',
'Cinza volumoso com preto simples: a proporção ampla embaixo é o que dá o toque contemporâneo.',
'["Adicionar overshirt em dias frescos", "Trocar tênis por bota"]'),
('Preto & Cinza Direto', 'O básico escuro sem pensar.', 'dia-a-dia', 'minimalista', 'calor', 'facil', 'preto', '/estilos/minimalista/15.jpg',
'["Camiseta preta", "Calça cinza reta", "Tênis ou sapato escuro", "Sem acessórios"]',
'A dupla preto + cinza resolve qualquer dia — é o look de menor esforço com maior taxa de acerto.',
'["Trocar camiseta por polo", "Clarear o cinza no verão"]'),
('Trilha Bordô', 'Montanha com cor de outono.', 'viagem', 'gorpcore', 'frio', 'facil', 'vinho', '/estilos/gorpcore/01.jpg',
'["Moletom técnico bordô com capuz", "Calça cáqui ampla", "Tênis de trilha", "Boné técnico"]',
'Bordô com cáqui é a paleta de outono na montanha — quente na cor, técnico na função.',
'["Trocar cáqui por preto", "Adicionar shell impermeável por cima"]'),
('Anorak Verde', 'Trilha urbana com shell clássica.', 'viagem', 'gorpcore', 'frio', 'intermediario', 'verde', '/estilos/gorpcore/02.jpg',
'["Anorak verde-oliva", "Calça técnica cinza", "Tênis trail", "Pochete transversal"]',
'O anorak verde é a peça gorpcore definitiva — funciona na serra e na cidade com a mesma naturalidade.',
'["Trocar calça técnica por cargo", "Camadas de fleece por baixo no frio"]'),
('Beira do Lago', 'Contemplação com camadas técnicas.', 'viagem', 'gorpcore', 'frio', 'facil', 'preto', '/estilos/gorpcore/04.jpg',
'["Jaqueta técnica preta", "Calça cinza clara ampla", "Tênis de trilha", "Gorro ou boné"]',
'Preto técnico com cinza claro é o gorpcore mais fácil de adotar — paleta urbana, função outdoor.',
'["Trocar jaqueta por fleece em dias secos", "Versão com calça preta total"]'),
('Fleece Creme', 'O abraço técnico do inverno.', 'dia-a-dia', 'gorpcore', 'frio', 'facil', 'bege', '/estilos/gorpcore/05.jpg',
'["Fleece creme felpudo", "Calça cinza ampla", "Tênis trail ou robusto", "Acessório técnico"]',
'O fleece claro é textura pura — com cinza embaixo, vira o look de frio mais confortável que existe.',
'["Trocar cinza por marrom para aquecer", "Adicionar colete por cima"]'),
('Puffer Urbano', 'Frio de cidade com volume técnico.', 'dia-a-dia', 'gorpcore', 'frio', 'facil', 'preto', '/estilos/gorpcore/06.jpg',
'["Puffer preto", "Moletom por baixo", "Calça cinza ampla", "Bota ou tênis robusto"]',
'O puffer preto com cinza é o inverno urbano resolvido — quente de verdade e impossível de errar.',
'["Trocar puffer por parka em chuva", "Adicionar gorro preto"]'),
('Camo Tech', 'Utilitário com estampa militar.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'intermediario', 'verde', '/estilos/gorpcore/07.jpg',
'["Moletom cinza com capuz", "Calça camuflada ampla", "Tênis branco", "Gorro claro"]',
'A camo entra como textura, não como fantasia — o moletom cinza neutraliza e o tênis branco ilumina.',
'["Trocar camo por verde-oliva liso", "Versão com bota no frio"]'),
('Shell Tech', 'Peça técnica com cor inesperada.', 'dia-a-dia', 'gorpcore', 'meia-estacao', 'avancado', 'cinza', '/estilos/gorpcore/08.jpg',
'["Shell técnica em tom suave", "Calça preta técnica", "Tênis de corrida chamativo", "Detalhes utilitários"]',
'Cores suaves em peças técnicas são o gorpcore avançado — o tênis vibrante é o ponto de energia do look.',
'["Neutralizar com tênis preto", "Trocar shell por fleece"]'),
('Puffer Marrom', 'The North Face de esquina.', 'dia-a-dia', 'gorpcore', 'frio', 'facil', 'marrom', '/estilos/gorpcore/09.jpg',
'["Puffer marrom", "Gorro preto", "Jeans cinza lavado", "Tênis robusto"]',
'O puffer marrom foge do preto óbvio — com denim lavado, o look fica urbano com alma outdoor.',
'["Trocar jeans por calça técnica", "Camadas de fleece por baixo"]'),
('Tonal Terra Tech', 'Monocromático técnico de frio.', 'dia-a-dia', 'gorpcore', 'frio', 'intermediario', 'marrom', '/estilos/gorpcore/10.jpg',
'["Fleece marrom", "Calça marrom ampla", "Tênis branco para respirar", "Bolsa transversal"]',
'Terra sobre terra com tênis branco: o monocromático gorpcore que parece styling de editorial.',
'["Quebrar com gorro preto", "Trocar tênis branco por bota"]'),
('Estrada de Neve', 'Frio extremo com azul técnico.', 'viagem', 'gorpcore', 'frio', 'intermediario', 'azul', '/estilos/gorpcore/12.jpg',
'["Puffer azul", "Calça técnica marrom ou terra", "Bota impermeável", "Balaclava ou gorro"]',
'Azul com terra é contraste de expedição — cores que aparecem na paisagem gelada sem gritar.',
'["Trocar puffer por shell + fleece", "Versão urbana com jeans"]'),
('Névoa', 'Trilha molhada com camuflagem suave.', 'viagem', 'gorpcore', 'frio', 'avancado', 'verde', '/estilos/gorpcore/13.jpg',
'["Anorak verde", "Calça de estampa desbotada", "Tênis trail", "Capuz fechado"]',
'Tons que somem na neblina: o look técnico que abraça a paisagem em vez de competir com ela.',
'["Simplificar com calça lisa", "Adicionar galochas em lama"]'),
('Shell P&B', 'Contraste técnico de montanha.', 'viagem', 'gorpcore', 'frio', 'intermediario', 'preto', '/estilos/gorpcore/14.jpg',
'["Shell preta e branca", "Calça técnica escura", "Tênis de trilha", "Luvas técnicas"]',
'O bloco preto e branco em peça técnica é gráfico e funcional — visual de expedição com leitura urbana.',
'["Versão toda preta", "Trocar shell por puffer em frio seco"]'),
('Montanha Total', 'Pico nevado com proteção máxima.', 'viagem', 'gorpcore', 'frio', 'intermediario', 'preto', '/estilos/gorpcore/15.jpg',
'["Shell preta fechada", "Calça cinza técnica", "Bota ou trail de neve", "Balaclava"]',
'Cada peça tem função e o estilo nasce disso — o gorpcore raiz é vestir a montanha e caminhar pela cidade.',
'["Aliviar camadas na cidade", "Adicionar cor no gorro"]'),
('Camurça 70s', 'Setentista urbano com camurça.', 'dia-a-dia', 'vintage', 'meia-estacao', 'intermediario', 'marrom', '/estilos/vintage/01.jpg',
'["Jaqueta de camurça marrom", "Camisa clara aberta", "Jeans reto de lavagem média", "Bota ou sapato de couro"]',
'Camurça com denim é a fórmula setentista que nunca sai — as texturas fazem o trabalho todo.',
'["Trocar camisa por camiseta gráfica", "Versão de frio com gola alta"]'),
('Couro & Flare', 'Noite com pegada setentista.', 'noite', 'vintage', 'meia-estacao', 'avancado', 'marrom', '/estilos/vintage/02.jpg',
'["Jaqueta de couro marrom", "Camiseta escura", "Jeans escuro levemente flare", "Bota de couro"]',
'O leve flare na barra muda a silhueta inteira — com couro marrom, o look tem alma de vinil e bar antigo.',
'["Trocar flare por reto clássico", "Adicionar corrente discreta"]'),
('Gráfica Lavada', 'Anos 90 em estado bruto.', 'dia-a-dia', 'vintage', 'calor', 'facil', 'cinza', '/estilos/vintage/03.jpg',
'["Camiseta branca com gráfico vintage", "Jeans super lavado amplo", "Tênis preto retrô", "Bolsa transversal"]',
'A lavagem estourada do denim é a peça de personalidade — a camiseta gráfica completa a cápsula do tempo.',
'["Trocar gráfico por liso para suavizar", "Adicionar boné desbotado"]'),
('Rugby Garimpado', 'Colegial de brechó.', 'faculdade', 'vintage', 'meia-estacao', 'facil', 'azul', '/estilos/vintage/05.jpg',
'["Rugby listrada vintage", "Jeans baggy claro", "Tênis branco retrô", "Mochila ou bolsa usada"]',
'A rugby de brechó com baggy é o visual de campus dos anos 90 — despretensioso e cheio de história.',
'["Trocar baggy por reto", "Versão com moletom universitário"]'),
('Couro de Feira', 'Garimpo de inverno.', 'dia-a-dia', 'vintage', 'frio', 'intermediario', 'marrom', '/estilos/vintage/06.jpg',
'["Jaqueta de couro marrom vintage", "Camisa ou tricô por baixo", "Calça marrom ou jeans escuro", "Bota de couro"]',
'Couro envelhecido tem o que peça nova não tem: passado. O restante do look só precisa acompanhar em tons quentes.',
'["Trocar calça marrom por jeans cru", "Adicionar cachecol de lã"]'),
('Jaqueta Estampada', 'Peça única de garimpo.', 'dia-a-dia', 'vintage', 'meia-estacao', 'avancado', 'verde', '/estilos/vintage/07.jpg',
'["Jaqueta estampada vintage", "Camiseta branca", "Jeans claro amplo", "Tênis retrô"]',
'Quando a jaqueta é a estrela, todo o resto vira moldura — base branca e denim claro deixam a peça brilhar.',
'["Trocar jeans por calça de sarja", "Versão noturna com jeans escuro"]'),
('Biblioteca 90s', 'Intelectual retrô com cargo.', 'faculdade', 'vintage', 'meia-estacao', 'intermediario', 'verde', '/estilos/vintage/08.jpg',
'["Polo rugby listrada verde", "Calça cargo marrom", "Sapato ou tênis de camurça", "Óculos de armação fina"]',
'Listras retrô com cargo terrosa: o visual de quem passa a tarde entre estantes — confortável e com referência.',
'["Trocar cargo por chino", "Adicionar cardigan sobre os ombros"]'),
('Xadrez & Couro', 'Camadas de outono raiz.', 'dia-a-dia', 'vintage', 'frio', 'intermediario', 'marrom', '/estilos/vintage/09.jpg',
'["Jaqueta marrom", "Camisa xadrez por baixo", "Jeans escuro", "Bota de trabalho"]',
'O xadrez aparecendo pela gola é o detalhe vintage que aquece o look — fórmula de outono desde sempre.',
'["Trocar xadrez por flanela lisa", "Versão com trucker jacket"]'),
('Xadrez Verde', 'Dia relaxado com padrão clássico.', 'dia-a-dia', 'vintage', 'meia-estacao', 'facil', 'verde', '/estilos/vintage/10.jpg',
'["Camisa xadrez verde", "Calça navy ampla", "Tênis retrô verde", "Boné combinando"]',
'Xadrez verde com navy é combinação de catálogo antigo — cores que já nasceram combinando.',
'["Usar a camisa aberta sobre camiseta", "Trocar navy por jeans claro"]'),
('Defender', 'Aventura vintage de fim de semana.', 'viagem', 'vintage', 'meia-estacao', 'intermediario', 'marrom', '/estilos/vintage/11.jpg',
'["Jaqueta de couro marrom", "Camiseta ou tricô neutro", "Jeans de lavagem média", "Bota de couro"]',
'Couro, denim e bota: o kit de estrada clássico — combina com carro antigo, montanha e cidade pequena.',
'["Trocar bota por tênis retrô", "Adicionar boné de lona"]'),
('Ringer Amarela', 'Verão retrô com cor de época.', 'dia-a-dia', 'vintage', 'calor', 'intermediario', 'azul', '/estilos/vintage/12.jpg',
'["Ringer tee amarela vintage", "Jeans lavado amplo", "Tênis preto retrô", "Óculos escuros"]',
'A ringer amarela é puro 1974 — o denim lavado e o tênis baixo seguram a cor sem deixar o look fantasiado.',
'["Trocar amarela por ringer branca", "Versão com jorts"]'),
('Kombi Cinza', 'Estrada com conforto de época.', 'viagem', 'vintage', 'calor', 'facil', 'cinza', '/estilos/vintage/13.jpg',
'["Camiseta gráfica cinza", "Calça cargo cinza", "Tênis retrô", "Boné de lona"]',
'Tons de cinza com peças utilitárias: o look de viagem que já nasce com filtro analógico.',
'["Adicionar camisa aberta", "Trocar cargo por jeans claro"]'),
('Ringer & Pregas', 'Retrô esportivo elevado.', 'dia-a-dia', 'vintage', 'calor', 'facil', 'branco', '/estilos/vintage/14.jpg',
'["Ringer tee branca", "Calça navy de pregas", "Sapato ou tênis retrô", "Boné vermelho como acento"]',
'Camiseta esportiva com calça de pregas mistura décadas com elegância — o boné dá o ponto de cor exato.',
'["Tirar o boné para sobriedade", "Trocar pregas por chino"]'),
('Gráfica Creme', 'Verão com estampa de época.', 'dia-a-dia', 'vintage', 'calor', 'facil', 'bege', '/estilos/vintage/15.jpg',
'["Camiseta creme com gráfico vintage", "Calça navy ampla", "Mocassim ou tênis retrô", "Óculos de época"]',
'Creme com navy é a paleta vintage mais limpa — a estampa antiga conta a história, o resto sustenta.',
'["Trocar navy por jeans lavado", "Versão com bermuda de sarja"]'),
('Jersey de Época', 'Futebol vintage como estilo.', 'evento-casual', 'vintage', 'calor', 'intermediario', 'vinho', '/estilos/vintage/16.jpg',
'["Jersey de futebol vintage", "Calça cru ampla", "Sapato ou tênis retrô", "Óculos escuros"]',
'O jersey antigo com calça cru e sapato tira a camisa do estádio e coloca no editorial — nostalgia bem vestida.',
'["Trocar cru por jeans claro", "Versão com jorts no calor extremo"]');
